/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lowes.vendortools.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lowes.vendortools.model.Order;
import com.lowes.vendortools.model.ShipmentHandlingUnit;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Delivery
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-03T04:59:55.167Z[GMT]")
public class Delivery {
  @SerializedName("deliveryId")
  private String deliveryId = null;

  @SerializedName("destinationCountryName")
  private String destinationCountryName = null;

  @SerializedName("asnNumber")
  private Long asnNumber = null;

  @SerializedName("destinationNodeNumber")
  private String destinationNodeNumber = null;

  @SerializedName("destinationNodeName")
  private String destinationNodeName = null;

  @SerializedName("destinationNodeType")
  private String destinationNodeType = null;

  @SerializedName("destinationStopNumber")
  private Integer destinationStopNumber = null;

  @SerializedName("requiredDeliveryTimestamp")
  private String requiredDeliveryTimestamp = null;

  @SerializedName("estimatedToActualDeliveryTimestamp")
  private String estimatedToActualDeliveryTimestamp = null;

  @SerializedName("deliveryStatus")
  private String deliveryStatus = null;

  @SerializedName("primarySealId")
  private String primarySealId = null;

  @SerializedName("secondarySealId")
  private String secondarySealId = null;

  @SerializedName("agency")
  private String agency = null;

  @SerializedName("order")
  private List<Order> order = null;

  @SerializedName("shipmentHandlingUnit")
  private List<ShipmentHandlingUnit> shipmentHandlingUnit = null;

  @SerializedName("primarySealNumber")
  private String primarySealNumber = null;

  @SerializedName("secondarySealNumber")
  private String secondarySealNumber = null;

  public Delivery deliveryId(String deliveryId) {
    this.deliveryId = deliveryId;
    return this;
  }

   /**
   * Get deliveryId
   * @return deliveryId
  **/
  @Schema(required = true, description = "")
  public String getDeliveryId() {
    return deliveryId;
  }

  public void setDeliveryId(String deliveryId) {
    this.deliveryId = deliveryId;
  }

  public Delivery destinationCountryName(String destinationCountryName) {
    this.destinationCountryName = destinationCountryName;
    return this;
  }

   /**
   * Get destinationCountryName
   * @return destinationCountryName
  **/
  @Schema(description = "")
  public String getDestinationCountryName() {
    return destinationCountryName;
  }

  public void setDestinationCountryName(String destinationCountryName) {
    this.destinationCountryName = destinationCountryName;
  }

  public Delivery asnNumber(Long asnNumber) {
    this.asnNumber = asnNumber;
    return this;
  }

   /**
   * Get asnNumber
   * @return asnNumber
  **/
  @Schema(description = "")
  public Long getAsnNumber() {
    return asnNumber;
  }

  public void setAsnNumber(Long asnNumber) {
    this.asnNumber = asnNumber;
  }

  public Delivery destinationNodeNumber(String destinationNodeNumber) {
    this.destinationNodeNumber = destinationNodeNumber;
    return this;
  }

   /**
   * Get destinationNodeNumber
   * @return destinationNodeNumber
  **/
  @Schema(required = true, description = "")
  public String getDestinationNodeNumber() {
    return destinationNodeNumber;
  }

  public void setDestinationNodeNumber(String destinationNodeNumber) {
    this.destinationNodeNumber = destinationNodeNumber;
  }

  public Delivery destinationNodeName(String destinationNodeName) {
    this.destinationNodeName = destinationNodeName;
    return this;
  }

   /**
   * Get destinationNodeName
   * @return destinationNodeName
  **/
  @Schema(description = "")
  public String getDestinationNodeName() {
    return destinationNodeName;
  }

  public void setDestinationNodeName(String destinationNodeName) {
    this.destinationNodeName = destinationNodeName;
  }

  public Delivery destinationNodeType(String destinationNodeType) {
    this.destinationNodeType = destinationNodeType;
    return this;
  }

   /**
   * Get destinationNodeType
   * @return destinationNodeType
  **/
  @Schema(description = "")
  public String getDestinationNodeType() {
    return destinationNodeType;
  }

  public void setDestinationNodeType(String destinationNodeType) {
    this.destinationNodeType = destinationNodeType;
  }

  public Delivery destinationStopNumber(Integer destinationStopNumber) {
    this.destinationStopNumber = destinationStopNumber;
    return this;
  }

   /**
   * Get destinationStopNumber
   * @return destinationStopNumber
  **/
  @Schema(description = "")
  public Integer getDestinationStopNumber() {
    return destinationStopNumber;
  }

  public void setDestinationStopNumber(Integer destinationStopNumber) {
    this.destinationStopNumber = destinationStopNumber;
  }

  public Delivery requiredDeliveryTimestamp(String requiredDeliveryTimestamp) {
    this.requiredDeliveryTimestamp = requiredDeliveryTimestamp;
    return this;
  }

   /**
   * Get requiredDeliveryTimestamp
   * @return requiredDeliveryTimestamp
  **/
  @Schema(description = "")
  public String getRequiredDeliveryTimestamp() {
    return requiredDeliveryTimestamp;
  }

  public void setRequiredDeliveryTimestamp(String requiredDeliveryTimestamp) {
    this.requiredDeliveryTimestamp = requiredDeliveryTimestamp;
  }

  public Delivery estimatedToActualDeliveryTimestamp(String estimatedToActualDeliveryTimestamp) {
    this.estimatedToActualDeliveryTimestamp = estimatedToActualDeliveryTimestamp;
    return this;
  }

   /**
   * Get estimatedToActualDeliveryTimestamp
   * @return estimatedToActualDeliveryTimestamp
  **/
  @Schema(description = "")
  public String getEstimatedToActualDeliveryTimestamp() {
    return estimatedToActualDeliveryTimestamp;
  }

  public void setEstimatedToActualDeliveryTimestamp(String estimatedToActualDeliveryTimestamp) {
    this.estimatedToActualDeliveryTimestamp = estimatedToActualDeliveryTimestamp;
  }

  public Delivery deliveryStatus(String deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
    return this;
  }

   /**
   * Get deliveryStatus
   * @return deliveryStatus
  **/
  @Schema(description = "")
  public String getDeliveryStatus() {
    return deliveryStatus;
  }

  public void setDeliveryStatus(String deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
  }

  public Delivery primarySealId(String primarySealId) {
    this.primarySealId = primarySealId;
    return this;
  }

   /**
   * Get primarySealId
   * @return primarySealId
  **/
  @Schema(description = "")
  public String getPrimarySealId() {
    return primarySealId;
  }

  public void setPrimarySealId(String primarySealId) {
    this.primarySealId = primarySealId;
  }

  public Delivery secondarySealId(String secondarySealId) {
    this.secondarySealId = secondarySealId;
    return this;
  }

   /**
   * Get secondarySealId
   * @return secondarySealId
  **/
  @Schema(description = "")
  public String getSecondarySealId() {
    return secondarySealId;
  }

  public void setSecondarySealId(String secondarySealId) {
    this.secondarySealId = secondarySealId;
  }

  public Delivery agency(String agency) {
    this.agency = agency;
    return this;
  }

   /**
   * Get agency
   * @return agency
  **/
  @Schema(description = "")
  public String getAgency() {
    return agency;
  }

  public void setAgency(String agency) {
    this.agency = agency;
  }

  public Delivery order(List<Order> order) {
    this.order = order;
    return this;
  }

  public Delivery addOrderItem(Order orderItem) {
    if (this.order == null) {
      this.order = new ArrayList<Order>();
    }
    this.order.add(orderItem);
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @Schema(description = "")
  public List<Order> getOrder() {
    return order;
  }

  public void setOrder(List<Order> order) {
    this.order = order;
  }

  public Delivery shipmentHandlingUnit(List<ShipmentHandlingUnit> shipmentHandlingUnit) {
    this.shipmentHandlingUnit = shipmentHandlingUnit;
    return this;
  }

  public Delivery addShipmentHandlingUnitItem(ShipmentHandlingUnit shipmentHandlingUnitItem) {
    if (this.shipmentHandlingUnit == null) {
      this.shipmentHandlingUnit = new ArrayList<ShipmentHandlingUnit>();
    }
    this.shipmentHandlingUnit.add(shipmentHandlingUnitItem);
    return this;
  }

   /**
   * Get shipmentHandlingUnit
   * @return shipmentHandlingUnit
  **/
  @Schema(description = "")
  public List<ShipmentHandlingUnit> getShipmentHandlingUnit() {
    return shipmentHandlingUnit;
  }

  public void setShipmentHandlingUnit(List<ShipmentHandlingUnit> shipmentHandlingUnit) {
    this.shipmentHandlingUnit = shipmentHandlingUnit;
  }

  public Delivery primarySealNumber(String primarySealNumber) {
    this.primarySealNumber = primarySealNumber;
    return this;
  }

   /**
   * Get primarySealNumber
   * @return primarySealNumber
  **/
  @Schema(description = "")
  public String getPrimarySealNumber() {
    return primarySealNumber;
  }

  public void setPrimarySealNumber(String primarySealNumber) {
    this.primarySealNumber = primarySealNumber;
  }

  public Delivery secondarySealNumber(String secondarySealNumber) {
    this.secondarySealNumber = secondarySealNumber;
    return this;
  }

   /**
   * Get secondarySealNumber
   * @return secondarySealNumber
  **/
  @Schema(description = "")
  public String getSecondarySealNumber() {
    return secondarySealNumber;
  }

  public void setSecondarySealNumber(String secondarySealNumber) {
    this.secondarySealNumber = secondarySealNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Delivery delivery = (Delivery) o;
    return Objects.equals(this.deliveryId, delivery.deliveryId) &&
        Objects.equals(this.destinationCountryName, delivery.destinationCountryName) &&
        Objects.equals(this.asnNumber, delivery.asnNumber) &&
        Objects.equals(this.destinationNodeNumber, delivery.destinationNodeNumber) &&
        Objects.equals(this.destinationNodeName, delivery.destinationNodeName) &&
        Objects.equals(this.destinationNodeType, delivery.destinationNodeType) &&
        Objects.equals(this.destinationStopNumber, delivery.destinationStopNumber) &&
        Objects.equals(this.requiredDeliveryTimestamp, delivery.requiredDeliveryTimestamp) &&
        Objects.equals(this.estimatedToActualDeliveryTimestamp, delivery.estimatedToActualDeliveryTimestamp) &&
        Objects.equals(this.deliveryStatus, delivery.deliveryStatus) &&
        Objects.equals(this.primarySealId, delivery.primarySealId) &&
        Objects.equals(this.secondarySealId, delivery.secondarySealId) &&
        Objects.equals(this.agency, delivery.agency) &&
        Objects.equals(this.order, delivery.order) &&
        Objects.equals(this.shipmentHandlingUnit, delivery.shipmentHandlingUnit) &&
        Objects.equals(this.primarySealNumber, delivery.primarySealNumber) &&
        Objects.equals(this.secondarySealNumber, delivery.secondarySealNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryId, destinationCountryName, asnNumber, destinationNodeNumber, destinationNodeName, destinationNodeType, destinationStopNumber, requiredDeliveryTimestamp, estimatedToActualDeliveryTimestamp, deliveryStatus, primarySealId, secondarySealId, agency, order, shipmentHandlingUnit, primarySealNumber, secondarySealNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Delivery {\n");
    
    sb.append("    deliveryId: ").append(toIndentedString(deliveryId)).append("\n");
    sb.append("    destinationCountryName: ").append(toIndentedString(destinationCountryName)).append("\n");
    sb.append("    asnNumber: ").append(toIndentedString(asnNumber)).append("\n");
    sb.append("    destinationNodeNumber: ").append(toIndentedString(destinationNodeNumber)).append("\n");
    sb.append("    destinationNodeName: ").append(toIndentedString(destinationNodeName)).append("\n");
    sb.append("    destinationNodeType: ").append(toIndentedString(destinationNodeType)).append("\n");
    sb.append("    destinationStopNumber: ").append(toIndentedString(destinationStopNumber)).append("\n");
    sb.append("    requiredDeliveryTimestamp: ").append(toIndentedString(requiredDeliveryTimestamp)).append("\n");
    sb.append("    estimatedToActualDeliveryTimestamp: ").append(toIndentedString(estimatedToActualDeliveryTimestamp)).append("\n");
    sb.append("    deliveryStatus: ").append(toIndentedString(deliveryStatus)).append("\n");
    sb.append("    primarySealId: ").append(toIndentedString(primarySealId)).append("\n");
    sb.append("    secondarySealId: ").append(toIndentedString(secondarySealId)).append("\n");
    sb.append("    agency: ").append(toIndentedString(agency)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    shipmentHandlingUnit: ").append(toIndentedString(shipmentHandlingUnit)).append("\n");
    sb.append("    primarySealNumber: ").append(toIndentedString(primarySealNumber)).append("\n");
    sb.append("    secondarySealNumber: ").append(toIndentedString(secondarySealNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
