/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lowes.vendortools.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DetailStatusQuantity
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-03T04:59:55.167Z[GMT]")
public class DetailStatusQuantity {
  @SerializedName("dtlStatus")
  private String dtlStatus = null;

  @SerializedName("qty")
  private Integer qty = null;

  @SerializedName("absQtyIdc")
  private Boolean absQtyIdc = null;

  public DetailStatusQuantity dtlStatus(String dtlStatus) {
    this.dtlStatus = dtlStatus;
    return this;
  }

   /**
   * Get dtlStatus
   * @return dtlStatus
  **/
  @Schema(required = true, description = "")
  public String getDtlStatus() {
    return dtlStatus;
  }

  public void setDtlStatus(String dtlStatus) {
    this.dtlStatus = dtlStatus;
  }

  public DetailStatusQuantity qty(Integer qty) {
    this.qty = qty;
    return this;
  }

   /**
   * Get qty
   * @return qty
  **/
  @Schema(required = true, description = "")
  public Integer getQty() {
    return qty;
  }

  public void setQty(Integer qty) {
    this.qty = qty;
  }

  public DetailStatusQuantity absQtyIdc(Boolean absQtyIdc) {
    this.absQtyIdc = absQtyIdc;
    return this;
  }

   /**
   * Get absQtyIdc
   * @return absQtyIdc
  **/
  @Schema(description = "")
  public Boolean isAbsQtyIdc() {
    return absQtyIdc;
  }

  public void setAbsQtyIdc(Boolean absQtyIdc) {
    this.absQtyIdc = absQtyIdc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailStatusQuantity detailStatusQuantity = (DetailStatusQuantity) o;
    return Objects.equals(this.dtlStatus, detailStatusQuantity.dtlStatus) &&
        Objects.equals(this.qty, detailStatusQuantity.qty) &&
        Objects.equals(this.absQtyIdc, detailStatusQuantity.absQtyIdc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dtlStatus, qty, absQtyIdc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailStatusQuantity {\n");
    
    sb.append("    dtlStatus: ").append(toIndentedString(dtlStatus)).append("\n");
    sb.append("    qty: ").append(toIndentedString(qty)).append("\n");
    sb.append("    absQtyIdc: ").append(toIndentedString(absQtyIdc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
