/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lowes.vendortools.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DetailReferences
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-03T04:59:55.167Z[GMT]")
public class DetailReferences {
  @SerializedName("dtlRefType")
  private String dtlRefType = null;

  @SerializedName("dtlRefId")
  private String dtlRefId = null;

  public DetailReferences dtlRefType(String dtlRefType) {
    this.dtlRefType = dtlRefType;
    return this;
  }

   /**
   * Get dtlRefType
   * @return dtlRefType
  **/
  @Schema(required = true, description = "")
  public String getDtlRefType() {
    return dtlRefType;
  }

  public void setDtlRefType(String dtlRefType) {
    this.dtlRefType = dtlRefType;
  }

  public DetailReferences dtlRefId(String dtlRefId) {
    this.dtlRefId = dtlRefId;
    return this;
  }

   /**
   * Get dtlRefId
   * @return dtlRefId
  **/
  @Schema(required = true, description = "")
  public String getDtlRefId() {
    return dtlRefId;
  }

  public void setDtlRefId(String dtlRefId) {
    this.dtlRefId = dtlRefId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailReferences detailReferences = (DetailReferences) o;
    return Objects.equals(this.dtlRefType, detailReferences.dtlRefType) &&
        Objects.equals(this.dtlRefId, detailReferences.dtlRefId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dtlRefType, dtlRefId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailReferences {\n");
    
    sb.append("    dtlRefType: ").append(toIndentedString(dtlRefType)).append("\n");
    sb.append("    dtlRefId: ").append(toIndentedString(dtlRefId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
