/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lowes.vendortools.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lowes.vendortools.model.PackagingInfo;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * InboundHeader
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-03T04:59:55.167Z[GMT]")
public class InboundHeader {
  @SerializedName("transactionId")
  private String transactionId = null;

  @SerializedName("asnReceivedAt")
  private OffsetDateTime asnReceivedAt = null;

  @SerializedName("tnsPpsId")
  private String tnsPpsId = null;

  @SerializedName("asnHrcSruId")
  private String asnHrcSruId = null;

  @SerializedName("dstMthTxt")
  private String dstMthTxt = null;

  @SerializedName("orgTmZonTxt")
  private String orgTmZonTxt = null;

  @SerializedName("arvTmZonTxt")
  private String arvTmZonTxt = null;

  @SerializedName("shpMthPayId")
  private String shpMthPayId = null;

  @SerializedName("equipmentDescTxt")
  private String equipmentDescTxt = null;

  @SerializedName("equipmentId")
  private String equipmentId = null;

  @SerializedName("frgCaiTxt")
  private String frgCaiTxt = null;

  @SerializedName("cdkLocNbr")
  private String cdkLocNbr = null;

  @SerializedName("packagingInfo")
  private List<PackagingInfo> packagingInfo = null;

  @SerializedName("troMthId")
  private String troMthId = null;

  @SerializedName("stxErrCdTxt")
  private String stxErrCdTxt = null;

  @SerializedName("evpErrCdTxt")
  private String evpErrCdTxt = null;

  @SerializedName("gsCmcId")
  private String gsCmcId = null;

  @SerializedName("cmcQlfTxt")
  private String cmcQlfTxt = null;

  @SerializedName("pnrTesPdcIdc")
  private String pnrTesPdcIdc = null;

  @SerializedName("fileName")
  private String fileName = null;

  public InboundHeader transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @Schema(description = "")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public InboundHeader asnReceivedAt(OffsetDateTime asnReceivedAt) {
    this.asnReceivedAt = asnReceivedAt;
    return this;
  }

   /**
   * Get asnReceivedAt
   * @return asnReceivedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getAsnReceivedAt() {
    return asnReceivedAt;
  }

  public void setAsnReceivedAt(OffsetDateTime asnReceivedAt) {
    this.asnReceivedAt = asnReceivedAt;
  }

  public InboundHeader tnsPpsId(String tnsPpsId) {
    this.tnsPpsId = tnsPpsId;
    return this;
  }

   /**
   * Get tnsPpsId
   * @return tnsPpsId
  **/
  @Schema(description = "")
  public String getTnsPpsId() {
    return tnsPpsId;
  }

  public void setTnsPpsId(String tnsPpsId) {
    this.tnsPpsId = tnsPpsId;
  }

  public InboundHeader asnHrcSruId(String asnHrcSruId) {
    this.asnHrcSruId = asnHrcSruId;
    return this;
  }

   /**
   * Get asnHrcSruId
   * @return asnHrcSruId
  **/
  @Schema(description = "")
  public String getAsnHrcSruId() {
    return asnHrcSruId;
  }

  public void setAsnHrcSruId(String asnHrcSruId) {
    this.asnHrcSruId = asnHrcSruId;
  }

  public InboundHeader dstMthTxt(String dstMthTxt) {
    this.dstMthTxt = dstMthTxt;
    return this;
  }

   /**
   * Get dstMthTxt
   * @return dstMthTxt
  **/
  @Schema(description = "")
  public String getDstMthTxt() {
    return dstMthTxt;
  }

  public void setDstMthTxt(String dstMthTxt) {
    this.dstMthTxt = dstMthTxt;
  }

  public InboundHeader orgTmZonTxt(String orgTmZonTxt) {
    this.orgTmZonTxt = orgTmZonTxt;
    return this;
  }

   /**
   * Get orgTmZonTxt
   * @return orgTmZonTxt
  **/
  @Schema(description = "")
  public String getOrgTmZonTxt() {
    return orgTmZonTxt;
  }

  public void setOrgTmZonTxt(String orgTmZonTxt) {
    this.orgTmZonTxt = orgTmZonTxt;
  }

  public InboundHeader arvTmZonTxt(String arvTmZonTxt) {
    this.arvTmZonTxt = arvTmZonTxt;
    return this;
  }

   /**
   * Get arvTmZonTxt
   * @return arvTmZonTxt
  **/
  @Schema(description = "")
  public String getArvTmZonTxt() {
    return arvTmZonTxt;
  }

  public void setArvTmZonTxt(String arvTmZonTxt) {
    this.arvTmZonTxt = arvTmZonTxt;
  }

  public InboundHeader shpMthPayId(String shpMthPayId) {
    this.shpMthPayId = shpMthPayId;
    return this;
  }

   /**
   * Get shpMthPayId
   * @return shpMthPayId
  **/
  @Schema(description = "")
  public String getShpMthPayId() {
    return shpMthPayId;
  }

  public void setShpMthPayId(String shpMthPayId) {
    this.shpMthPayId = shpMthPayId;
  }

  public InboundHeader equipmentDescTxt(String equipmentDescTxt) {
    this.equipmentDescTxt = equipmentDescTxt;
    return this;
  }

   /**
   * Get equipmentDescTxt
   * @return equipmentDescTxt
  **/
  @Schema(description = "")
  public String getEquipmentDescTxt() {
    return equipmentDescTxt;
  }

  public void setEquipmentDescTxt(String equipmentDescTxt) {
    this.equipmentDescTxt = equipmentDescTxt;
  }

  public InboundHeader equipmentId(String equipmentId) {
    this.equipmentId = equipmentId;
    return this;
  }

   /**
   * Get equipmentId
   * @return equipmentId
  **/
  @Schema(description = "")
  public String getEquipmentId() {
    return equipmentId;
  }

  public void setEquipmentId(String equipmentId) {
    this.equipmentId = equipmentId;
  }

  public InboundHeader frgCaiTxt(String frgCaiTxt) {
    this.frgCaiTxt = frgCaiTxt;
    return this;
  }

   /**
   * Get frgCaiTxt
   * @return frgCaiTxt
  **/
  @Schema(description = "")
  public String getFrgCaiTxt() {
    return frgCaiTxt;
  }

  public void setFrgCaiTxt(String frgCaiTxt) {
    this.frgCaiTxt = frgCaiTxt;
  }

  public InboundHeader cdkLocNbr(String cdkLocNbr) {
    this.cdkLocNbr = cdkLocNbr;
    return this;
  }

   /**
   * Get cdkLocNbr
   * @return cdkLocNbr
  **/
  @Schema(description = "")
  public String getCdkLocNbr() {
    return cdkLocNbr;
  }

  public void setCdkLocNbr(String cdkLocNbr) {
    this.cdkLocNbr = cdkLocNbr;
  }

  public InboundHeader packagingInfo(List<PackagingInfo> packagingInfo) {
    this.packagingInfo = packagingInfo;
    return this;
  }

  public InboundHeader addPackagingInfoItem(PackagingInfo packagingInfoItem) {
    if (this.packagingInfo == null) {
      this.packagingInfo = new ArrayList<PackagingInfo>();
    }
    this.packagingInfo.add(packagingInfoItem);
    return this;
  }

   /**
   * Get packagingInfo
   * @return packagingInfo
  **/
  @Schema(description = "")
  public List<PackagingInfo> getPackagingInfo() {
    return packagingInfo;
  }

  public void setPackagingInfo(List<PackagingInfo> packagingInfo) {
    this.packagingInfo = packagingInfo;
  }

  public InboundHeader troMthId(String troMthId) {
    this.troMthId = troMthId;
    return this;
  }

   /**
   * Get troMthId
   * @return troMthId
  **/
  @Schema(description = "")
  public String getTroMthId() {
    return troMthId;
  }

  public void setTroMthId(String troMthId) {
    this.troMthId = troMthId;
  }

  public InboundHeader stxErrCdTxt(String stxErrCdTxt) {
    this.stxErrCdTxt = stxErrCdTxt;
    return this;
  }

   /**
   * Get stxErrCdTxt
   * @return stxErrCdTxt
  **/
  @Schema(description = "")
  public String getStxErrCdTxt() {
    return stxErrCdTxt;
  }

  public void setStxErrCdTxt(String stxErrCdTxt) {
    this.stxErrCdTxt = stxErrCdTxt;
  }

  public InboundHeader evpErrCdTxt(String evpErrCdTxt) {
    this.evpErrCdTxt = evpErrCdTxt;
    return this;
  }

   /**
   * Get evpErrCdTxt
   * @return evpErrCdTxt
  **/
  @Schema(description = "")
  public String getEvpErrCdTxt() {
    return evpErrCdTxt;
  }

  public void setEvpErrCdTxt(String evpErrCdTxt) {
    this.evpErrCdTxt = evpErrCdTxt;
  }

  public InboundHeader gsCmcId(String gsCmcId) {
    this.gsCmcId = gsCmcId;
    return this;
  }

   /**
   * Get gsCmcId
   * @return gsCmcId
  **/
  @Schema(description = "")
  public String getGsCmcId() {
    return gsCmcId;
  }

  public void setGsCmcId(String gsCmcId) {
    this.gsCmcId = gsCmcId;
  }

  public InboundHeader cmcQlfTxt(String cmcQlfTxt) {
    this.cmcQlfTxt = cmcQlfTxt;
    return this;
  }

   /**
   * Get cmcQlfTxt
   * @return cmcQlfTxt
  **/
  @Schema(description = "")
  public String getCmcQlfTxt() {
    return cmcQlfTxt;
  }

  public void setCmcQlfTxt(String cmcQlfTxt) {
    this.cmcQlfTxt = cmcQlfTxt;
  }

  public InboundHeader pnrTesPdcIdc(String pnrTesPdcIdc) {
    this.pnrTesPdcIdc = pnrTesPdcIdc;
    return this;
  }

   /**
   * Get pnrTesPdcIdc
   * @return pnrTesPdcIdc
  **/
  @Schema(description = "")
  public String getPnrTesPdcIdc() {
    return pnrTesPdcIdc;
  }

  public void setPnrTesPdcIdc(String pnrTesPdcIdc) {
    this.pnrTesPdcIdc = pnrTesPdcIdc;
  }

  public InboundHeader fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
  @Schema(description = "")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InboundHeader inboundHeader = (InboundHeader) o;
    return Objects.equals(this.transactionId, inboundHeader.transactionId) &&
        Objects.equals(this.asnReceivedAt, inboundHeader.asnReceivedAt) &&
        Objects.equals(this.tnsPpsId, inboundHeader.tnsPpsId) &&
        Objects.equals(this.asnHrcSruId, inboundHeader.asnHrcSruId) &&
        Objects.equals(this.dstMthTxt, inboundHeader.dstMthTxt) &&
        Objects.equals(this.orgTmZonTxt, inboundHeader.orgTmZonTxt) &&
        Objects.equals(this.arvTmZonTxt, inboundHeader.arvTmZonTxt) &&
        Objects.equals(this.shpMthPayId, inboundHeader.shpMthPayId) &&
        Objects.equals(this.equipmentDescTxt, inboundHeader.equipmentDescTxt) &&
        Objects.equals(this.equipmentId, inboundHeader.equipmentId) &&
        Objects.equals(this.frgCaiTxt, inboundHeader.frgCaiTxt) &&
        Objects.equals(this.cdkLocNbr, inboundHeader.cdkLocNbr) &&
        Objects.equals(this.packagingInfo, inboundHeader.packagingInfo) &&
        Objects.equals(this.troMthId, inboundHeader.troMthId) &&
        Objects.equals(this.stxErrCdTxt, inboundHeader.stxErrCdTxt) &&
        Objects.equals(this.evpErrCdTxt, inboundHeader.evpErrCdTxt) &&
        Objects.equals(this.gsCmcId, inboundHeader.gsCmcId) &&
        Objects.equals(this.cmcQlfTxt, inboundHeader.cmcQlfTxt) &&
        Objects.equals(this.pnrTesPdcIdc, inboundHeader.pnrTesPdcIdc) &&
        Objects.equals(this.fileName, inboundHeader.fileName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, asnReceivedAt, tnsPpsId, asnHrcSruId, dstMthTxt, orgTmZonTxt, arvTmZonTxt, shpMthPayId, equipmentDescTxt, equipmentId, frgCaiTxt, cdkLocNbr, packagingInfo, troMthId, stxErrCdTxt, evpErrCdTxt, gsCmcId, cmcQlfTxt, pnrTesPdcIdc, fileName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InboundHeader {\n");
    
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    asnReceivedAt: ").append(toIndentedString(asnReceivedAt)).append("\n");
    sb.append("    tnsPpsId: ").append(toIndentedString(tnsPpsId)).append("\n");
    sb.append("    asnHrcSruId: ").append(toIndentedString(asnHrcSruId)).append("\n");
    sb.append("    dstMthTxt: ").append(toIndentedString(dstMthTxt)).append("\n");
    sb.append("    orgTmZonTxt: ").append(toIndentedString(orgTmZonTxt)).append("\n");
    sb.append("    arvTmZonTxt: ").append(toIndentedString(arvTmZonTxt)).append("\n");
    sb.append("    shpMthPayId: ").append(toIndentedString(shpMthPayId)).append("\n");
    sb.append("    equipmentDescTxt: ").append(toIndentedString(equipmentDescTxt)).append("\n");
    sb.append("    equipmentId: ").append(toIndentedString(equipmentId)).append("\n");
    sb.append("    frgCaiTxt: ").append(toIndentedString(frgCaiTxt)).append("\n");
    sb.append("    cdkLocNbr: ").append(toIndentedString(cdkLocNbr)).append("\n");
    sb.append("    packagingInfo: ").append(toIndentedString(packagingInfo)).append("\n");
    sb.append("    troMthId: ").append(toIndentedString(troMthId)).append("\n");
    sb.append("    stxErrCdTxt: ").append(toIndentedString(stxErrCdTxt)).append("\n");
    sb.append("    evpErrCdTxt: ").append(toIndentedString(evpErrCdTxt)).append("\n");
    sb.append("    gsCmcId: ").append(toIndentedString(gsCmcId)).append("\n");
    sb.append("    cmcQlfTxt: ").append(toIndentedString(cmcQlfTxt)).append("\n");
    sb.append("    pnrTesPdcIdc: ").append(toIndentedString(pnrTesPdcIdc)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
