/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lowes.vendortools.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lowes.vendortools.model.HandlingUnitDetail;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ShipmentHandlingUnit
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-03T04:59:55.167Z[GMT]")
public class ShipmentHandlingUnit {
  @SerializedName("uId")
  private String uId = null;

  @SerializedName("uType")
  private String uType = null;

  @SerializedName("barCdId")
  private String barCdId = null;

  @SerializedName("barCdType")
  private String barCdType = null;

  @SerializedName("uWgt")
  private Float uWgt = null;

  @SerializedName("uCube")
  private Float uCube = null;

  @SerializedName("uLen")
  private Float uLen = null;

  @SerializedName("uWid")
  private Float uWid = null;

  @SerializedName("uHgt")
  private Float uHgt = null;

  @SerializedName("uStatus")
  private String uStatus = null;

  @SerializedName("uDtl")
  private List<HandlingUnitDetail> uDtl = null;

  @SerializedName("puId")
  private Integer puId = null;

  public ShipmentHandlingUnit uId(String uId) {
    this.uId = uId;
    return this;
  }

   /**
   * Get uId
   * @return uId
  **/
  @Schema(required = true, description = "")
  public String getUId() {
    return uId;
  }

  public void setUId(String uId) {
    this.uId = uId;
  }

  public ShipmentHandlingUnit uType(String uType) {
    this.uType = uType;
    return this;
  }

   /**
   * Get uType
   * @return uType
  **/
  @Schema(required = true, description = "")
  public String getUType() {
    return uType;
  }

  public void setUType(String uType) {
    this.uType = uType;
  }

  public ShipmentHandlingUnit barCdId(String barCdId) {
    this.barCdId = barCdId;
    return this;
  }

   /**
   * Get barCdId
   * @return barCdId
  **/
  @Schema(description = "")
  public String getBarCdId() {
    return barCdId;
  }

  public void setBarCdId(String barCdId) {
    this.barCdId = barCdId;
  }

  public ShipmentHandlingUnit barCdType(String barCdType) {
    this.barCdType = barCdType;
    return this;
  }

   /**
   * Get barCdType
   * @return barCdType
  **/
  @Schema(description = "")
  public String getBarCdType() {
    return barCdType;
  }

  public void setBarCdType(String barCdType) {
    this.barCdType = barCdType;
  }

  public ShipmentHandlingUnit uWgt(Float uWgt) {
    this.uWgt = uWgt;
    return this;
  }

   /**
   * Get uWgt
   * @return uWgt
  **/
  @Schema(description = "")
  public Float getUWgt() {
    return uWgt;
  }

  public void setUWgt(Float uWgt) {
    this.uWgt = uWgt;
  }

  public ShipmentHandlingUnit uCube(Float uCube) {
    this.uCube = uCube;
    return this;
  }

   /**
   * Get uCube
   * @return uCube
  **/
  @Schema(description = "")
  public Float getUCube() {
    return uCube;
  }

  public void setUCube(Float uCube) {
    this.uCube = uCube;
  }

  public ShipmentHandlingUnit uLen(Float uLen) {
    this.uLen = uLen;
    return this;
  }

   /**
   * Get uLen
   * @return uLen
  **/
  @Schema(description = "")
  public Float getULen() {
    return uLen;
  }

  public void setULen(Float uLen) {
    this.uLen = uLen;
  }

  public ShipmentHandlingUnit uWid(Float uWid) {
    this.uWid = uWid;
    return this;
  }

   /**
   * Get uWid
   * @return uWid
  **/
  @Schema(description = "")
  public Float getUWid() {
    return uWid;
  }

  public void setUWid(Float uWid) {
    this.uWid = uWid;
  }

  public ShipmentHandlingUnit uHgt(Float uHgt) {
    this.uHgt = uHgt;
    return this;
  }

   /**
   * Get uHgt
   * @return uHgt
  **/
  @Schema(description = "")
  public Float getUHgt() {
    return uHgt;
  }

  public void setUHgt(Float uHgt) {
    this.uHgt = uHgt;
  }

  public ShipmentHandlingUnit uStatus(String uStatus) {
    this.uStatus = uStatus;
    return this;
  }

   /**
   * Get uStatus
   * @return uStatus
  **/
  @Schema(description = "")
  public String getUStatus() {
    return uStatus;
  }

  public void setUStatus(String uStatus) {
    this.uStatus = uStatus;
  }

  public ShipmentHandlingUnit uDtl(List<HandlingUnitDetail> uDtl) {
    this.uDtl = uDtl;
    return this;
  }

  public ShipmentHandlingUnit addUDtlItem(HandlingUnitDetail uDtlItem) {
    if (this.uDtl == null) {
      this.uDtl = new ArrayList<HandlingUnitDetail>();
    }
    this.uDtl.add(uDtlItem);
    return this;
  }

   /**
   * Get uDtl
   * @return uDtl
  **/
  @Schema(description = "")
  public List<HandlingUnitDetail> getUDtl() {
    return uDtl;
  }

  public void setUDtl(List<HandlingUnitDetail> uDtl) {
    this.uDtl = uDtl;
  }

  public ShipmentHandlingUnit puId(Integer puId) {
    this.puId = puId;
    return this;
  }

   /**
   * Get puId
   * @return puId
  **/
  @Schema(required = true, description = "")
  public Integer getPuId() {
    return puId;
  }

  public void setPuId(Integer puId) {
    this.puId = puId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentHandlingUnit shipmentHandlingUnit = (ShipmentHandlingUnit) o;
    return Objects.equals(this.uId, shipmentHandlingUnit.uId) &&
        Objects.equals(this.uType, shipmentHandlingUnit.uType) &&
        Objects.equals(this.barCdId, shipmentHandlingUnit.barCdId) &&
        Objects.equals(this.barCdType, shipmentHandlingUnit.barCdType) &&
        Objects.equals(this.uWgt, shipmentHandlingUnit.uWgt) &&
        Objects.equals(this.uCube, shipmentHandlingUnit.uCube) &&
        Objects.equals(this.uLen, shipmentHandlingUnit.uLen) &&
        Objects.equals(this.uWid, shipmentHandlingUnit.uWid) &&
        Objects.equals(this.uHgt, shipmentHandlingUnit.uHgt) &&
        Objects.equals(this.uStatus, shipmentHandlingUnit.uStatus) &&
        Objects.equals(this.uDtl, shipmentHandlingUnit.uDtl) &&
        Objects.equals(this.puId, shipmentHandlingUnit.puId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uId, uType, barCdId, barCdType, uWgt, uCube, uLen, uWid, uHgt, uStatus, uDtl, puId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentHandlingUnit {\n");
    
    sb.append("    uId: ").append(toIndentedString(uId)).append("\n");
    sb.append("    uType: ").append(toIndentedString(uType)).append("\n");
    sb.append("    barCdId: ").append(toIndentedString(barCdId)).append("\n");
    sb.append("    barCdType: ").append(toIndentedString(barCdType)).append("\n");
    sb.append("    uWgt: ").append(toIndentedString(uWgt)).append("\n");
    sb.append("    uCube: ").append(toIndentedString(uCube)).append("\n");
    sb.append("    uLen: ").append(toIndentedString(uLen)).append("\n");
    sb.append("    uWid: ").append(toIndentedString(uWid)).append("\n");
    sb.append("    uHgt: ").append(toIndentedString(uHgt)).append("\n");
    sb.append("    uStatus: ").append(toIndentedString(uStatus)).append("\n");
    sb.append("    uDtl: ").append(toIndentedString(uDtl)).append("\n");
    sb.append("    puId: ").append(toIndentedString(puId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
