/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ASNData;
import io.swagger.client.model.InboundHeader;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ASNInformation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-03T04:59:55.167Z[GMT]")
public class ASNInformation {
  @SerializedName("ASN")
  private ASNData ASN = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("IncomingHeader")
  private InboundHeader incomingHeader = null;

  public ASNInformation ASN(ASNData ASN) {
    this.ASN = ASN;
    return this;
  }

   /**
   * Get ASN
   * @return ASN
  **/
  @Schema(required = true, description = "")
  public ASNData getASN() {
    return ASN;
  }

  public void setASN(ASNData ASN) {
    this.ASN = ASN;
  }

  public ASNInformation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ASNInformation incomingHeader(InboundHeader incomingHeader) {
    this.incomingHeader = incomingHeader;
    return this;
  }

   /**
   * Get incomingHeader
   * @return incomingHeader
  **/
  @Schema(description = "")
  public InboundHeader getIncomingHeader() {
    return incomingHeader;
  }

  public void setIncomingHeader(InboundHeader incomingHeader) {
    this.incomingHeader = incomingHeader;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ASNInformation asNInformation = (ASNInformation) o;
    return Objects.equals(this.ASN, asNInformation.ASN) &&
        Objects.equals(this.id, asNInformation.id) &&
        Objects.equals(this.incomingHeader, asNInformation.incomingHeader);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ASN, id, incomingHeader);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ASNInformation {\n");
    
    sb.append("    ASN: ").append(toIndentedString(ASN)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    incomingHeader: ").append(toIndentedString(incomingHeader)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
