/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.FreightDestinationNodeAddress;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FreightMovement
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-03T04:59:55.167Z[GMT]")
public class FreightMovement {
  @SerializedName("freightStatus")
  private String freightStatus = null;

  @SerializedName("freightMovementId")
  private String freightMovementId = null;

  @SerializedName("freightMovementSequenceNumber")
  private Integer freightMovementSequenceNumber = null;

  @SerializedName("shippingMode")
  private String shippingMode = null;

  @SerializedName("lowesFreightPayIndicator")
  private Boolean lowesFreightPayIndicator = null;

  @SerializedName("carrierScacId")
  private String carrierScacId = null;

  @SerializedName("billOfLadingId")
  private String billOfLadingId = null;

  @SerializedName("freightDestinationNodeNumber")
  private Long freightDestinationNodeNumber = null;

  @SerializedName("freightDestinationNodeName")
  private String freightDestinationNodeName = null;

  @SerializedName("freightDestinationNodeAddress")
  private FreightDestinationNodeAddress freightDestinationNodeAddress = null;

  @SerializedName("freightDestinationNodeType")
  private String freightDestinationNodeType = null;

  public FreightMovement freightStatus(String freightStatus) {
    this.freightStatus = freightStatus;
    return this;
  }

   /**
   * Get freightStatus
   * @return freightStatus
  **/
  @Schema(description = "")
  public String getFreightStatus() {
    return freightStatus;
  }

  public void setFreightStatus(String freightStatus) {
    this.freightStatus = freightStatus;
  }

  public FreightMovement freightMovementId(String freightMovementId) {
    this.freightMovementId = freightMovementId;
    return this;
  }

   /**
   * Get freightMovementId
   * @return freightMovementId
  **/
  @Schema(description = "")
  public String getFreightMovementId() {
    return freightMovementId;
  }

  public void setFreightMovementId(String freightMovementId) {
    this.freightMovementId = freightMovementId;
  }

  public FreightMovement freightMovementSequenceNumber(Integer freightMovementSequenceNumber) {
    this.freightMovementSequenceNumber = freightMovementSequenceNumber;
    return this;
  }

   /**
   * Get freightMovementSequenceNumber
   * @return freightMovementSequenceNumber
  **/
  @Schema(description = "")
  public Integer getFreightMovementSequenceNumber() {
    return freightMovementSequenceNumber;
  }

  public void setFreightMovementSequenceNumber(Integer freightMovementSequenceNumber) {
    this.freightMovementSequenceNumber = freightMovementSequenceNumber;
  }

  public FreightMovement shippingMode(String shippingMode) {
    this.shippingMode = shippingMode;
    return this;
  }

   /**
   * Get shippingMode
   * @return shippingMode
  **/
  @Schema(description = "")
  public String getShippingMode() {
    return shippingMode;
  }

  public void setShippingMode(String shippingMode) {
    this.shippingMode = shippingMode;
  }

  public FreightMovement lowesFreightPayIndicator(Boolean lowesFreightPayIndicator) {
    this.lowesFreightPayIndicator = lowesFreightPayIndicator;
    return this;
  }

   /**
   * Get lowesFreightPayIndicator
   * @return lowesFreightPayIndicator
  **/
  @Schema(description = "")
  public Boolean isLowesFreightPayIndicator() {
    return lowesFreightPayIndicator;
  }

  public void setLowesFreightPayIndicator(Boolean lowesFreightPayIndicator) {
    this.lowesFreightPayIndicator = lowesFreightPayIndicator;
  }

  public FreightMovement carrierScacId(String carrierScacId) {
    this.carrierScacId = carrierScacId;
    return this;
  }

   /**
   * Get carrierScacId
   * @return carrierScacId
  **/
  @Schema(description = "")
  public String getCarrierScacId() {
    return carrierScacId;
  }

  public void setCarrierScacId(String carrierScacId) {
    this.carrierScacId = carrierScacId;
  }

  public FreightMovement billOfLadingId(String billOfLadingId) {
    this.billOfLadingId = billOfLadingId;
    return this;
  }

   /**
   * Get billOfLadingId
   * @return billOfLadingId
  **/
  @Schema(description = "")
  public String getBillOfLadingId() {
    return billOfLadingId;
  }

  public void setBillOfLadingId(String billOfLadingId) {
    this.billOfLadingId = billOfLadingId;
  }

  public FreightMovement freightDestinationNodeNumber(Long freightDestinationNodeNumber) {
    this.freightDestinationNodeNumber = freightDestinationNodeNumber;
    return this;
  }

   /**
   * Get freightDestinationNodeNumber
   * @return freightDestinationNodeNumber
  **/
  @Schema(description = "")
  public Long getFreightDestinationNodeNumber() {
    return freightDestinationNodeNumber;
  }

  public void setFreightDestinationNodeNumber(Long freightDestinationNodeNumber) {
    this.freightDestinationNodeNumber = freightDestinationNodeNumber;
  }

  public FreightMovement freightDestinationNodeName(String freightDestinationNodeName) {
    this.freightDestinationNodeName = freightDestinationNodeName;
    return this;
  }

   /**
   * Get freightDestinationNodeName
   * @return freightDestinationNodeName
  **/
  @Schema(description = "")
  public String getFreightDestinationNodeName() {
    return freightDestinationNodeName;
  }

  public void setFreightDestinationNodeName(String freightDestinationNodeName) {
    this.freightDestinationNodeName = freightDestinationNodeName;
  }

  public FreightMovement freightDestinationNodeAddress(FreightDestinationNodeAddress freightDestinationNodeAddress) {
    this.freightDestinationNodeAddress = freightDestinationNodeAddress;
    return this;
  }

   /**
   * Get freightDestinationNodeAddress
   * @return freightDestinationNodeAddress
  **/
  @Schema(description = "")
  public FreightDestinationNodeAddress getFreightDestinationNodeAddress() {
    return freightDestinationNodeAddress;
  }

  public void setFreightDestinationNodeAddress(FreightDestinationNodeAddress freightDestinationNodeAddress) {
    this.freightDestinationNodeAddress = freightDestinationNodeAddress;
  }

  public FreightMovement freightDestinationNodeType(String freightDestinationNodeType) {
    this.freightDestinationNodeType = freightDestinationNodeType;
    return this;
  }

   /**
   * Get freightDestinationNodeType
   * @return freightDestinationNodeType
  **/
  @Schema(description = "")
  public String getFreightDestinationNodeType() {
    return freightDestinationNodeType;
  }

  public void setFreightDestinationNodeType(String freightDestinationNodeType) {
    this.freightDestinationNodeType = freightDestinationNodeType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FreightMovement freightMovement = (FreightMovement) o;
    return Objects.equals(this.freightStatus, freightMovement.freightStatus) &&
        Objects.equals(this.freightMovementId, freightMovement.freightMovementId) &&
        Objects.equals(this.freightMovementSequenceNumber, freightMovement.freightMovementSequenceNumber) &&
        Objects.equals(this.shippingMode, freightMovement.shippingMode) &&
        Objects.equals(this.lowesFreightPayIndicator, freightMovement.lowesFreightPayIndicator) &&
        Objects.equals(this.carrierScacId, freightMovement.carrierScacId) &&
        Objects.equals(this.billOfLadingId, freightMovement.billOfLadingId) &&
        Objects.equals(this.freightDestinationNodeNumber, freightMovement.freightDestinationNodeNumber) &&
        Objects.equals(this.freightDestinationNodeName, freightMovement.freightDestinationNodeName) &&
        Objects.equals(this.freightDestinationNodeAddress, freightMovement.freightDestinationNodeAddress) &&
        Objects.equals(this.freightDestinationNodeType, freightMovement.freightDestinationNodeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(freightStatus, freightMovementId, freightMovementSequenceNumber, shippingMode, lowesFreightPayIndicator, carrierScacId, billOfLadingId, freightDestinationNodeNumber, freightDestinationNodeName, freightDestinationNodeAddress, freightDestinationNodeType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FreightMovement {\n");
    
    sb.append("    freightStatus: ").append(toIndentedString(freightStatus)).append("\n");
    sb.append("    freightMovementId: ").append(toIndentedString(freightMovementId)).append("\n");
    sb.append("    freightMovementSequenceNumber: ").append(toIndentedString(freightMovementSequenceNumber)).append("\n");
    sb.append("    shippingMode: ").append(toIndentedString(shippingMode)).append("\n");
    sb.append("    lowesFreightPayIndicator: ").append(toIndentedString(lowesFreightPayIndicator)).append("\n");
    sb.append("    carrierScacId: ").append(toIndentedString(carrierScacId)).append("\n");
    sb.append("    billOfLadingId: ").append(toIndentedString(billOfLadingId)).append("\n");
    sb.append("    freightDestinationNodeNumber: ").append(toIndentedString(freightDestinationNodeNumber)).append("\n");
    sb.append("    freightDestinationNodeName: ").append(toIndentedString(freightDestinationNodeName)).append("\n");
    sb.append("    freightDestinationNodeAddress: ").append(toIndentedString(freightDestinationNodeAddress)).append("\n");
    sb.append("    freightDestinationNodeType: ").append(toIndentedString(freightDestinationNodeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
