/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * HandlingUnitDetail
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-03T04:59:55.167Z[GMT]")
public class HandlingUnitDetail {
  @SerializedName("ordNbr")
  private Long ordNbr = null;

  @SerializedName("lineNbr")
  private Long lineNbr = null;

  @SerializedName("qty")
  private Long qty = null;

  public HandlingUnitDetail ordNbr(Long ordNbr) {
    this.ordNbr = ordNbr;
    return this;
  }

   /**
   * Get ordNbr
   * @return ordNbr
  **/
  @Schema(description = "")
  public Long getOrdNbr() {
    return ordNbr;
  }

  public void setOrdNbr(Long ordNbr) {
    this.ordNbr = ordNbr;
  }

  public HandlingUnitDetail lineNbr(Long lineNbr) {
    this.lineNbr = lineNbr;
    return this;
  }

   /**
   * Get lineNbr
   * @return lineNbr
  **/
  @Schema(description = "")
  public Long getLineNbr() {
    return lineNbr;
  }

  public void setLineNbr(Long lineNbr) {
    this.lineNbr = lineNbr;
  }

  public HandlingUnitDetail qty(Long qty) {
    this.qty = qty;
    return this;
  }

   /**
   * Get qty
   * @return qty
  **/
  @Schema(description = "")
  public Long getQty() {
    return qty;
  }

  public void setQty(Long qty) {
    this.qty = qty;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HandlingUnitDetail handlingUnitDetail = (HandlingUnitDetail) o;
    return Objects.equals(this.ordNbr, handlingUnitDetail.ordNbr) &&
        Objects.equals(this.lineNbr, handlingUnitDetail.lineNbr) &&
        Objects.equals(this.qty, handlingUnitDetail.qty);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ordNbr, lineNbr, qty);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HandlingUnitDetail {\n");
    
    sb.append("    ordNbr: ").append(toIndentedString(ordNbr)).append("\n");
    sb.append("    lineNbr: ").append(toIndentedString(lineNbr)).append("\n");
    sb.append("    qty: ").append(toIndentedString(qty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
