/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.OrderDetail;
import io.swagger.client.model.OrderReferences;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Order
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-03T04:59:55.167Z[GMT]")
public class Order {
  @SerializedName("ordNbr")
  private String ordNbr = null;

  @SerializedName("ordSource")
  private String ordSource = null;

  @SerializedName("orderType")
  private String orderType = null;

  @SerializedName("xDockNodeNumber")
  private Long xDockNodeNumber = null;

  @SerializedName("orderReferences")
  private List<OrderReferences> orderReferences = null;

  @SerializedName("ordWgt")
  private Float ordWgt = null;

  @SerializedName("ordCube")
  private Float ordCube = null;

  @SerializedName("ordStatus")
  private String ordStatus = null;

  @SerializedName("ordDetail")
  private List<OrderDetail> ordDetail = null;

  @SerializedName("poDestinationNodeNumber")
  private Long poDestinationNodeNumber = null;

  @SerializedName("asnCreateTimestamp")
  private String asnCreateTimestamp = null;

  @SerializedName("asnUpdateTimestamp")
  private String asnUpdateTimestamp = null;

  @SerializedName("hrcId")
  private String hrcId = null;

  public Order ordNbr(String ordNbr) {
    this.ordNbr = ordNbr;
    return this;
  }

   /**
   * Get ordNbr
   * @return ordNbr
  **/
  @Schema(required = true, description = "")
  public String getOrdNbr() {
    return ordNbr;
  }

  public void setOrdNbr(String ordNbr) {
    this.ordNbr = ordNbr;
  }

  public Order ordSource(String ordSource) {
    this.ordSource = ordSource;
    return this;
  }

   /**
   * Get ordSource
   * @return ordSource
  **/
  @Schema(description = "")
  public String getOrdSource() {
    return ordSource;
  }

  public void setOrdSource(String ordSource) {
    this.ordSource = ordSource;
  }

  public Order orderType(String orderType) {
    this.orderType = orderType;
    return this;
  }

   /**
   * Get orderType
   * @return orderType
  **/
  @Schema(description = "")
  public String getOrderType() {
    return orderType;
  }

  public void setOrderType(String orderType) {
    this.orderType = orderType;
  }

  public Order xDockNodeNumber(Long xDockNodeNumber) {
    this.xDockNodeNumber = xDockNodeNumber;
    return this;
  }

   /**
   * Get xDockNodeNumber
   * @return xDockNodeNumber
  **/
  @Schema(description = "")
  public Long getXDockNodeNumber() {
    return xDockNodeNumber;
  }

  public void setXDockNodeNumber(Long xDockNodeNumber) {
    this.xDockNodeNumber = xDockNodeNumber;
  }

  public Order orderReferences(List<OrderReferences> orderReferences) {
    this.orderReferences = orderReferences;
    return this;
  }

  public Order addOrderReferencesItem(OrderReferences orderReferencesItem) {
    if (this.orderReferences == null) {
      this.orderReferences = new ArrayList<OrderReferences>();
    }
    this.orderReferences.add(orderReferencesItem);
    return this;
  }

   /**
   * Get orderReferences
   * @return orderReferences
  **/
  @Schema(description = "")
  public List<OrderReferences> getOrderReferences() {
    return orderReferences;
  }

  public void setOrderReferences(List<OrderReferences> orderReferences) {
    this.orderReferences = orderReferences;
  }

  public Order ordWgt(Float ordWgt) {
    this.ordWgt = ordWgt;
    return this;
  }

   /**
   * Get ordWgt
   * @return ordWgt
  **/
  @Schema(description = "")
  public Float getOrdWgt() {
    return ordWgt;
  }

  public void setOrdWgt(Float ordWgt) {
    this.ordWgt = ordWgt;
  }

  public Order ordCube(Float ordCube) {
    this.ordCube = ordCube;
    return this;
  }

   /**
   * Get ordCube
   * @return ordCube
  **/
  @Schema(description = "")
  public Float getOrdCube() {
    return ordCube;
  }

  public void setOrdCube(Float ordCube) {
    this.ordCube = ordCube;
  }

  public Order ordStatus(String ordStatus) {
    this.ordStatus = ordStatus;
    return this;
  }

   /**
   * Get ordStatus
   * @return ordStatus
  **/
  @Schema(required = true, description = "")
  public String getOrdStatus() {
    return ordStatus;
  }

  public void setOrdStatus(String ordStatus) {
    this.ordStatus = ordStatus;
  }

  public Order ordDetail(List<OrderDetail> ordDetail) {
    this.ordDetail = ordDetail;
    return this;
  }

  public Order addOrdDetailItem(OrderDetail ordDetailItem) {
    if (this.ordDetail == null) {
      this.ordDetail = new ArrayList<OrderDetail>();
    }
    this.ordDetail.add(ordDetailItem);
    return this;
  }

   /**
   * Get ordDetail
   * @return ordDetail
  **/
  @Schema(description = "")
  public List<OrderDetail> getOrdDetail() {
    return ordDetail;
  }

  public void setOrdDetail(List<OrderDetail> ordDetail) {
    this.ordDetail = ordDetail;
  }

  public Order poDestinationNodeNumber(Long poDestinationNodeNumber) {
    this.poDestinationNodeNumber = poDestinationNodeNumber;
    return this;
  }

   /**
   * Get poDestinationNodeNumber
   * @return poDestinationNodeNumber
  **/
  @Schema(description = "")
  public Long getPoDestinationNodeNumber() {
    return poDestinationNodeNumber;
  }

  public void setPoDestinationNodeNumber(Long poDestinationNodeNumber) {
    this.poDestinationNodeNumber = poDestinationNodeNumber;
  }

  public Order asnCreateTimestamp(String asnCreateTimestamp) {
    this.asnCreateTimestamp = asnCreateTimestamp;
    return this;
  }

   /**
   * Get asnCreateTimestamp
   * @return asnCreateTimestamp
  **/
  @Schema(description = "")
  public String getAsnCreateTimestamp() {
    return asnCreateTimestamp;
  }

  public void setAsnCreateTimestamp(String asnCreateTimestamp) {
    this.asnCreateTimestamp = asnCreateTimestamp;
  }

  public Order asnUpdateTimestamp(String asnUpdateTimestamp) {
    this.asnUpdateTimestamp = asnUpdateTimestamp;
    return this;
  }

   /**
   * Get asnUpdateTimestamp
   * @return asnUpdateTimestamp
  **/
  @Schema(description = "")
  public String getAsnUpdateTimestamp() {
    return asnUpdateTimestamp;
  }

  public void setAsnUpdateTimestamp(String asnUpdateTimestamp) {
    this.asnUpdateTimestamp = asnUpdateTimestamp;
  }

  public Order hrcId(String hrcId) {
    this.hrcId = hrcId;
    return this;
  }

   /**
   * Get hrcId
   * @return hrcId
  **/
  @Schema(description = "")
  public String getHrcId() {
    return hrcId;
  }

  public void setHrcId(String hrcId) {
    this.hrcId = hrcId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Order order = (Order) o;
    return Objects.equals(this.ordNbr, order.ordNbr) &&
        Objects.equals(this.ordSource, order.ordSource) &&
        Objects.equals(this.orderType, order.orderType) &&
        Objects.equals(this.xDockNodeNumber, order.xDockNodeNumber) &&
        Objects.equals(this.orderReferences, order.orderReferences) &&
        Objects.equals(this.ordWgt, order.ordWgt) &&
        Objects.equals(this.ordCube, order.ordCube) &&
        Objects.equals(this.ordStatus, order.ordStatus) &&
        Objects.equals(this.ordDetail, order.ordDetail) &&
        Objects.equals(this.poDestinationNodeNumber, order.poDestinationNodeNumber) &&
        Objects.equals(this.asnCreateTimestamp, order.asnCreateTimestamp) &&
        Objects.equals(this.asnUpdateTimestamp, order.asnUpdateTimestamp) &&
        Objects.equals(this.hrcId, order.hrcId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ordNbr, ordSource, orderType, xDockNodeNumber, orderReferences, ordWgt, ordCube, ordStatus, ordDetail, poDestinationNodeNumber, asnCreateTimestamp, asnUpdateTimestamp, hrcId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Order {\n");
    
    sb.append("    ordNbr: ").append(toIndentedString(ordNbr)).append("\n");
    sb.append("    ordSource: ").append(toIndentedString(ordSource)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    xDockNodeNumber: ").append(toIndentedString(xDockNodeNumber)).append("\n");
    sb.append("    orderReferences: ").append(toIndentedString(orderReferences)).append("\n");
    sb.append("    ordWgt: ").append(toIndentedString(ordWgt)).append("\n");
    sb.append("    ordCube: ").append(toIndentedString(ordCube)).append("\n");
    sb.append("    ordStatus: ").append(toIndentedString(ordStatus)).append("\n");
    sb.append("    ordDetail: ").append(toIndentedString(ordDetail)).append("\n");
    sb.append("    poDestinationNodeNumber: ").append(toIndentedString(poDestinationNodeNumber)).append("\n");
    sb.append("    asnCreateTimestamp: ").append(toIndentedString(asnCreateTimestamp)).append("\n");
    sb.append("    asnUpdateTimestamp: ").append(toIndentedString(asnUpdateTimestamp)).append("\n");
    sb.append("    hrcId: ").append(toIndentedString(hrcId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
