/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OrderReferences
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-03T04:59:55.167Z[GMT]")
public class OrderReferences {
  @SerializedName("orderReferenceType")
  private String orderReferenceType = null;

  @SerializedName("orderReferenceId")
  private String orderReferenceId = null;

  public OrderReferences orderReferenceType(String orderReferenceType) {
    this.orderReferenceType = orderReferenceType;
    return this;
  }

   /**
   * Get orderReferenceType
   * @return orderReferenceType
  **/
  @Schema(required = true, description = "")
  public String getOrderReferenceType() {
    return orderReferenceType;
  }

  public void setOrderReferenceType(String orderReferenceType) {
    this.orderReferenceType = orderReferenceType;
  }

  public OrderReferences orderReferenceId(String orderReferenceId) {
    this.orderReferenceId = orderReferenceId;
    return this;
  }

   /**
   * Get orderReferenceId
   * @return orderReferenceId
  **/
  @Schema(required = true, description = "")
  public String getOrderReferenceId() {
    return orderReferenceId;
  }

  public void setOrderReferenceId(String orderReferenceId) {
    this.orderReferenceId = orderReferenceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderReferences orderReferences = (OrderReferences) o;
    return Objects.equals(this.orderReferenceType, orderReferences.orderReferenceType) &&
        Objects.equals(this.orderReferenceId, orderReferences.orderReferenceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderReferenceType, orderReferenceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderReferences {\n");
    
    sb.append("    orderReferenceType: ").append(toIndentedString(orderReferenceType)).append("\n");
    sb.append("    orderReferenceId: ").append(toIndentedString(orderReferenceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
