/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.DetailReferences;
import io.swagger.client.model.DetailStatusQuantity;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * OrderDetail
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-03T04:59:55.167Z[GMT]")
public class OrderDetail {
  @SerializedName("lineNbr")
  private Integer lineNbr = null;

  @SerializedName("dtlId")
  private String dtlId = null;

  @SerializedName("dtlRefs")
  private List<DetailReferences> dtlRefs = null;

  @SerializedName("dtlType")
  private String dtlType = null;

  @SerializedName("dtlStatusQty")
  private List<DetailStatusQuantity> dtlStatusQty = new ArrayList<DetailStatusQuantity>();

  @SerializedName("hrcId")
  private String hrcId = null;

  @SerializedName("barcodeId")
  private String barcodeId = null;

  @SerializedName("prtHrcId")
  private String prtHrcId = null;

  public OrderDetail lineNbr(Integer lineNbr) {
    this.lineNbr = lineNbr;
    return this;
  }

   /**
   * Get lineNbr
   * @return lineNbr
  **/
  @Schema(required = true, description = "")
  public Integer getLineNbr() {
    return lineNbr;
  }

  public void setLineNbr(Integer lineNbr) {
    this.lineNbr = lineNbr;
  }

  public OrderDetail dtlId(String dtlId) {
    this.dtlId = dtlId;
    return this;
  }

   /**
   * Get dtlId
   * @return dtlId
  **/
  @Schema(required = true, description = "")
  public String getDtlId() {
    return dtlId;
  }

  public void setDtlId(String dtlId) {
    this.dtlId = dtlId;
  }

  public OrderDetail dtlRefs(List<DetailReferences> dtlRefs) {
    this.dtlRefs = dtlRefs;
    return this;
  }

  public OrderDetail addDtlRefsItem(DetailReferences dtlRefsItem) {
    if (this.dtlRefs == null) {
      this.dtlRefs = new ArrayList<DetailReferences>();
    }
    this.dtlRefs.add(dtlRefsItem);
    return this;
  }

   /**
   * Get dtlRefs
   * @return dtlRefs
  **/
  @Schema(description = "")
  public List<DetailReferences> getDtlRefs() {
    return dtlRefs;
  }

  public void setDtlRefs(List<DetailReferences> dtlRefs) {
    this.dtlRefs = dtlRefs;
  }

  public OrderDetail dtlType(String dtlType) {
    this.dtlType = dtlType;
    return this;
  }

   /**
   * Get dtlType
   * @return dtlType
  **/
  @Schema(required = true, description = "")
  public String getDtlType() {
    return dtlType;
  }

  public void setDtlType(String dtlType) {
    this.dtlType = dtlType;
  }

  public OrderDetail dtlStatusQty(List<DetailStatusQuantity> dtlStatusQty) {
    this.dtlStatusQty = dtlStatusQty;
    return this;
  }

  public OrderDetail addDtlStatusQtyItem(DetailStatusQuantity dtlStatusQtyItem) {
    this.dtlStatusQty.add(dtlStatusQtyItem);
    return this;
  }

   /**
   * Get dtlStatusQty
   * @return dtlStatusQty
  **/
  @Schema(required = true, description = "")
  public List<DetailStatusQuantity> getDtlStatusQty() {
    return dtlStatusQty;
  }

  public void setDtlStatusQty(List<DetailStatusQuantity> dtlStatusQty) {
    this.dtlStatusQty = dtlStatusQty;
  }

  public OrderDetail hrcId(String hrcId) {
    this.hrcId = hrcId;
    return this;
  }

   /**
   * Get hrcId
   * @return hrcId
  **/
  @Schema(description = "")
  public String getHrcId() {
    return hrcId;
  }

  public void setHrcId(String hrcId) {
    this.hrcId = hrcId;
  }

  public OrderDetail barcodeId(String barcodeId) {
    this.barcodeId = barcodeId;
    return this;
  }

   /**
   * Get barcodeId
   * @return barcodeId
  **/
  @Schema(description = "")
  public String getBarcodeId() {
    return barcodeId;
  }

  public void setBarcodeId(String barcodeId) {
    this.barcodeId = barcodeId;
  }

  public OrderDetail prtHrcId(String prtHrcId) {
    this.prtHrcId = prtHrcId;
    return this;
  }

   /**
   * Get prtHrcId
   * @return prtHrcId
  **/
  @Schema(description = "")
  public String getPrtHrcId() {
    return prtHrcId;
  }

  public void setPrtHrcId(String prtHrcId) {
    this.prtHrcId = prtHrcId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderDetail orderDetail = (OrderDetail) o;
    return Objects.equals(this.lineNbr, orderDetail.lineNbr) &&
        Objects.equals(this.dtlId, orderDetail.dtlId) &&
        Objects.equals(this.dtlRefs, orderDetail.dtlRefs) &&
        Objects.equals(this.dtlType, orderDetail.dtlType) &&
        Objects.equals(this.dtlStatusQty, orderDetail.dtlStatusQty) &&
        Objects.equals(this.hrcId, orderDetail.hrcId) &&
        Objects.equals(this.barcodeId, orderDetail.barcodeId) &&
        Objects.equals(this.prtHrcId, orderDetail.prtHrcId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lineNbr, dtlId, dtlRefs, dtlType, dtlStatusQty, hrcId, barcodeId, prtHrcId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderDetail {\n");
    
    sb.append("    lineNbr: ").append(toIndentedString(lineNbr)).append("\n");
    sb.append("    dtlId: ").append(toIndentedString(dtlId)).append("\n");
    sb.append("    dtlRefs: ").append(toIndentedString(dtlRefs)).append("\n");
    sb.append("    dtlType: ").append(toIndentedString(dtlType)).append("\n");
    sb.append("    dtlStatusQty: ").append(toIndentedString(dtlStatusQty)).append("\n");
    sb.append("    hrcId: ").append(toIndentedString(hrcId)).append("\n");
    sb.append("    barcodeId: ").append(toIndentedString(barcodeId)).append("\n");
    sb.append("    prtHrcId: ").append(toIndentedString(prtHrcId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
