/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PackagingInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-03T04:59:55.167Z[GMT]")
public class PackagingInfo {
  @SerializedName("pckType")
  private String pckType = null;

  @SerializedName("pckCount")
  private Integer pckCount = null;

  public PackagingInfo pckType(String pckType) {
    this.pckType = pckType;
    return this;
  }

   /**
   * Get pckType
   * @return pckType
  **/
  @Schema(description = "")
  public String getPckType() {
    return pckType;
  }

  public void setPckType(String pckType) {
    this.pckType = pckType;
  }

  public PackagingInfo pckCount(Integer pckCount) {
    this.pckCount = pckCount;
    return this;
  }

   /**
   * Get pckCount
   * @return pckCount
  **/
  @Schema(description = "")
  public Integer getPckCount() {
    return pckCount;
  }

  public void setPckCount(Integer pckCount) {
    this.pckCount = pckCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackagingInfo packagingInfo = (PackagingInfo) o;
    return Objects.equals(this.pckType, packagingInfo.pckType) &&
        Objects.equals(this.pckCount, packagingInfo.pckCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pckType, pckCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackagingInfo {\n");
    
    sb.append("    pckType: ").append(toIndentedString(pckType)).append("\n");
    sb.append("    pckCount: ").append(toIndentedString(pckCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
