/*
 * ASN Service
 * This app provides REST APIs for ASN Service
 *
 * OpenAPI spec version: v3
 * Contact: firstname.lastname@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ASNInformation;
import io.swagger.client.model.ASNServiceResponseDTO;
import io.swagger.client.model.ValidatedASNView;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AsnMasterApi
 */
@Ignore
public class AsnMasterApiTest {

    private final AsnMasterApi api = new AsnMasterApi();

    /**
     * Get ASN Information By Transaction Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getASNStatusByTransactionIdTest() throws ApiException {
        String txnId = null;
        ValidatedASNView response = api.getASNStatusByTransactionId(txnId);

        // TODO: test validations
    }
    /**
     * Get ASN Information By Order Number
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getASNStatusByTransactionIdAndOrderNumberTest() throws ApiException {
        String orderNumber = null;
        ValidatedASNView response = api.getASNStatusByTransactionIdAndOrderNumber(orderNumber);

        // TODO: test validations
    }
    /**
     * Get ASN Information By  Order Number and LoadId
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getASNStatusByTransactionIdAndOrderNumberAndLoadIdTest() throws ApiException {
        String orderNumber = null;
        String loadId = null;
        ValidatedASNView response = api.getASNStatusByTransactionIdAndOrderNumberAndLoadId(orderNumber, loadId);

        // TODO: test validations
    }
    /**
     * POST ASN Data
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postAsnTest() throws ApiException {
        ASNInformation body = null;
        ASNServiceResponseDTO response = api.postAsn(body);

        // TODO: test validations
    }
}
